# Generated by Django 2.2.10 on 2020-04-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_noteitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteitem',
            name='title',
            field=models.TextField(),
        ),
    ]
