# Generated by Django 2.2.10 on 2020-04-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20200423_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteitem',
            name='color',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
